<a href="https://colab.research.google.com/github/qorwlghks/26-DATA/blob/main/03w_numpy_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.linspace(2,3)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [2]:
np.linspace(2,3,2)

array([2., 3.])

In [3]:
np.linspace(2,3,3,retstep=True)

(array([2. , 2.5, 3. ]), np.float64(0.5))

In [4]:
a = np.linspace(2,3,3,retstep=True)
a[1]

np.float64(0.5)

In [6]:
np.linspace(2,3,3,retstep=True,endpoint=False)

(array([2.        , 2.33333333, 2.66666667]), np.float64(0.3333333333333333))

In [7]:
print( (3-2) / 50)

0.02


### numpy 주요 함수

In [8]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [9]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.zeros(2,3)

TypeError: Cannot interpret '3' as a data type

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.full([2,3], 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [14]:
np.full([2,3], (1,2,3,))

array([[1, 2, 3],
       [1, 2, 3]])

In [15]:
np.full([2,3],(1,2))

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

In [16]:
np.full([3,4],range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [17]:
np.full([4,3], fill_value=np.arange(4).reshape(4,1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [18]:
import numpy as np

a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [19]:
print(a[3])
print(a[-2])

9
64


In [20]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [21]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


### 고급 색인

In [23]:
import numpy as np
x = np.arange(10)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
x[1]

np.int64(1)

In [25]:
x[:5]

array([0, 1, 2, 3, 4])

In [26]:
x[ [2,3,2,5,8]]
np.array([2,3,2,5,8])

NameError: name 'array' is not defined

In [27]:
int(x[0,1])
1

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [28]:
x[...,2:8]

array([2, 3, 4, 5, 6, 7])

In [29]:
x[0,1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [30]:
x[ [0], '[1]']

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [31]:
from numpy import arange

x = arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [32]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [33]:
x[0,1]

np.int64(1)

In [34]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [35]:
x[ [1,3] [2]]

IndexError: list index out of range

In [36]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [37]:
x[ [0,2,4], [1]]

array([ 1, 17, 33])

In [38]:
x[ [0,2,4], :2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [39]:
x[ [0,2,4], [1,1,1]]

array([ 1, 17, 33])

In [40]:
x[ [0,2,4], [1,1]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [41]:
a[2:4, 3:7]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [42]:
a = np.arange(40).reshape(5,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [43]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [44]:
a[[2,3]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [45]:
a[np.arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [46]:
a[np.arange(2,4)][:,[1,0]]

array([[17, 16],
       [25, 24]])

In [47]:
a[np.arange(2,4)][:, [1,0,3,5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29]])

In [48]:
a[np.arange(2,5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [49]:
a[np.arange(2,5)][:, arange(-1,-8,-1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

In [50]:
a[[2,3,4]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])