<a href="https://colab.research.google.com/github/qorwlghks/26-BDA/blob/main/04w_arrary_stack_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
c = np.arange(1,6,2)
c

array([1, 3, 5])

In [7]:
import numpy as np
np.hstack((a))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
np.column_stack( (a,c))

array([1,2,3,4,],
      [5,6,7,8],
      [9,10,11,12])

NameError: name 'array' is not defined

In [10]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [27]:
np.column_stack( (a,b))
np.array([[1,4],
         [2,5],
         [3,4]])

array([[1, 4],
       [2, 5],
       [3, 4]])

In [28]:
import numpy as np
x = np.array([1,2,3])
y= np.array([4,5,6])
np.array([[1,2,3]])

array([[1, 2, 3]])

In [17]:
y

array([4, 5, 6])

In [18]:
x.shape, y.shape

((3,), (3,))

In [19]:
np.column_stack( (x,y))


array([[1, 4],
       [2, 5],
       [3, 6]])

In [20]:
np.c_[x,y]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
np.c_[x, np.full_like(x, 10), np.full_like(x, 20), y]

array([[ 1, 10, 20,  4],
       [ 2, 10, 20,  5],
       [ 3, 10, 20,  6]])

In [26]:
np.column_stack( (x, np.full_like(x, 10), np.full_like(x, 20), y))

array([[ 1, 10, 20,  4],
       [ 2, 10, 20,  5],
       [ 3, 10, 20,  6]])

In [30]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

In [31]:
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [32]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [34]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])

In [35]:
np.c_[x,y]

array([[1, 2, 3, 4, 5, 6]])

In [36]:
np.column_stack((x,y))

array([[1, 2, 3, 4, 5, 6]])

In [37]:
np.c_[x,10,20,y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [38]:
np.column_stack((x,10,20,y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [45]:
import numpy as np

rg = np.random.default_rng(1)
rg
rg.random()

0.5118216247002567

In [53]:
rg.random()

0.5495936876730595

In [54]:
rg.random(5)

array([0.02755911, 0.75351311, 0.53814331, 0.32973172, 0.7884287 ])

In [56]:
rg.random((4,3))

array([[0.30319483, 0.45349789, 0.1340417 ],
       [0.40311299, 0.20345524, 0.26231334],
       [0.75036467, 0.28040876, 0.48519097],
       [0.9807372 , 0.96165719, 0.72478994]])

In [58]:
import numpy as np

rg = np.random.default_rng(1)
rg.integers(low=0, high=10, size=3)

array([4, 5, 7])

In [65]:
C

array([[10, 17,  9,  7],
       [ 1,  9, 12, 15],
       [17,  4, 11, 16]])

In [67]:
rg.integers(1,7,(3,4))

array([[2, 3, 6, 4],
       [4, 5, 4, 6],
       [5, 1, 1, 4]])

In [68]:
import numpy as np

rg = np.random.default_rng(1)
rg.standard_normal(3)

array([0.34558419, 0.82161814, 0.33043708])

In [76]:
rg.standard_normal((3,4))

array([[-1.04879657e-03,  4.45573554e-01,  4.68404336e-01,
         8.76242196e-01],
       [ 2.56485627e-01, -9.48283390e-02, -2.58848065e-01,
         1.05574280e+00],
       [-2.25085428e+00, -1.38655325e-01,  3.30001040e-02,
        -1.42534896e+00]])

### 배열 결합 연습

In [78]:
a = np.arange(1,4)
b = np.arange(4,7)
c = np.arange(7,10)
a,b,c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [79]:
p = np.arange(1,7).reshape(2,3)
q = np.arange(11,17).reshape(2,3)
r = np.arange(21,27).reshape(2,3)
p,q,r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [80]:
np.vstack( (a,b,c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
np.vstack( (p, q, r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [82]:
np.hstack( (a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
p,q,r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [83]:
np.hstack( (p, q, r))

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [85]:
a,b,c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [86]:
np.column_stack((a,b,c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [87]:
np.column_stack((p,q,r))

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [88]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
np.concatenate((a,b,c)), axis=1

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (3888045539.py, line 1)

In [91]:
np.concatenate((a,b,c), axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
np.concatenate((a,b,c), axis=-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
np.concatenate((p,q,r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [94]:
np.concatenate((p,q,r), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [95]:
np.concatenate((p,q,r), axis=1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [96]:
np.concatenate((p,q,r), axis=-1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [97]:
np.concatenate((p,q,r), axis=None)

array([ 1,  2,  3,  4,  5,  6, 11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25,
       26])

In [98]:
np.c_[a,b,c]

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [99]:
np.column_stack( (a,b,c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [100]:
np.c_[p,q,r]

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [101]:
np.r_[a,b,c]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
np.r_[p,q,r]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [104]:
np.vstack((p,q,r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [105]:
import numpy as np

a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [106]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [110]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [112]:
import numpy as np

x = np.array([1,2,3])
y = np.array([5,6,7])
np.vstack((x,y))

array([[1, 2, 3],
       [5, 6, 7]])

In [113]:
import numpy as np

a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [114]:
b = np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [115]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [116]:
np.hstack((np.arange(3),np.arange(10,15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

In [118]:
x = np.array([1,2,3])
y = np.array([10,20,30])
np.column_stack((x,y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [119]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [124]:
import numpy as np

a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [125]:
import numpy as np

b = np.arange(10,22).reshape(4,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [126]:
np.row_stack((a,b))

/tmp/ipykernel_13542/1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [127]:
import numpy as np

a = np.array([1,2])
b = np.array([3,4])
c = np.array([5,6])

In [128]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6])

In [129]:
np.concatenate((a,b,c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [130]:
np.concatenate((a,b,c), axis=None)

array([1, 2, 3, 4, 5, 6])